###################
# ENV VARS:
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Check for new releases
# Check automatically for new releases (new version)

on:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch release version
        id: fetch-version
        run: |
          curl -sL https://raw.githubusercontent.com/strapi/strapi/master/packages/core/strapi/package.json | jq -r ".version" > release-versions/strapi-latest.txt
          echo ::set-output name=version::$(cat release-versions/strapi-latest.txt)

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New auto release v${{steps.fetch-version.outputs.version}}